config/routes.rb
Rails.application.routes.draw do

root to: 'welcome#index'
get "welcome/index" =>  'welcome#index'
  devise_for :users
  resources :users, only: [:show] do
  end
  resources :topics do
    resources :bookmarks, except: [:index]
  end
  resources :bookmarks, only: [] do
    resources :likes, only: [:create, :destroy]
  end
  resources :incoming, only: [:create]

  #Incoming mail Controller
  post :incoming, to: "incoming#create"
end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  attr_reader :embed_service
  require 'uri'
  require 'json'
  has_many :likes, dependent: :destroy
  belongs_to :user
  belongs_to :topic
  validates :description, length: {minimum: 10}, presence: true
  validates :url, length: { minimum: 10 }, presence: true, format: { with: URI.regexp}
  before_create :url_format




  def url_format
    url.scan(URI.regexp)
      URI.regexp =~ url
  end

  def embedly
    @embed_service ||= EmbedlyService.new
    embed_service.embed(url)
  end
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :bookmark
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :user
  has_many :bookmarks
  default_scope { order('updated_at DESC') }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :topics
         has_many :bookmarks
         has_many :likes, dependent: :destroy
         has_many :liked_bookmarks, through: :likes, source: :bookmark

         validates :email, presence: true
         validates :password, presence: true

         def liked(bookmark)
           likes.where(bookmark_id: bookmark.id).first
         end


       end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :authenticate_user!
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) << :username
  end

  def after_sign_in_path_for(users)
  current_user
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def show
    @topic = Topic.find(params[:topic_id])
    @bookmark = Bookmark.find(params[:id])

  end

  def new
    @user = User.find(params[current_user])
    @topic = Topic.find(params[:topic_id])
    @bookmark = current_user.bookmarks.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @bookmark = current_user.bookmarks.build(bookmark_params)
    @bookmark.topic = @topic
    authorize @bookmark
    if @bookmark.save
      flash[:notice] = "Bookmark saved"
      redirect_to @topic
    else
      flash[:error] = "There was an error saving your bookmark"
      redirect_to request.referer
    end
  end

  def edit
    @bookmark = Bookmark.find(params[:id])
  end
  def update
    @bookmark = Bookmark.find(params[:id])
    @bookmark.assign_attributes(bookmark_params)
    authorize @bookmark

    if @bookmark.save
      flash[:notice] = "Bookmark was updated."
      redirect_to [@bookmark.topic, @bookmark]
    else
      flash[:error] = "An error has occured. Please try again."
      render :edit
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    @bookmark = topic.bookmarks.find(params[:id])
    authorize @bookmark

    if @bookmark.destroy
      flash[:notice] = "\"#{@bookmark.url}\" was deleted successfully."
      redirect_to request.referer
    else
      flash[:error] = "bookmark was not delete, please try again"
      render :new
    end
    end




  private

  def bookmark_params
    params.require(:bookmark).permit(:url, :description)
  end


end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
  # http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_action :verify_authenticity_token, only: [:create]
  skip_before_filter :authenticate_user!

  def create
    @user = User.find_by(email: params[:sender])
    @topic = Topic.find_by(user_id: @user, title: params[:subject])
    @url = "http://#{params['body-plain']}"

    @user = User.create(email: params[:sender], password: "#{params[:title]}_blocmarks") if @user.nil?
    @topic = Topic.create(title: params[:subject], user_id: @user.id) if @topic.nil?

    @bookmark = Bookmark.create( url: params['body-plain'])
    @bookmark.update_attributes(topic_id: @topic.id)

    head 200
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @bookmark = Bookmark.find(params[:bookmark_id])
    like = current_user.likes.build(bookmark: @bookmark)

    authorize Like
    if like.save
      flash[:notice] = "bookmark liked"
    else
      flash[:error] = "Unsuccessful, try again."
    end
    redirect_to request.referer
  end



  def destroy

    like = Like.find(params[:id])
    authorize Like
    if like.destroy
      flash[:notice] = "bookmark unliked"
    else
      flash[:error] = "Unsuccessful, try again."
    end
    redirect_to request.referer
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController


  def show
    @topic = Topic.find(params[:id])
    @new_bookmark = Bookmark.new
    

  end

  def new
    @topic = Topic.new
  end

  def create


      @topic = Topic.new(topic_params)
      @topic.user = current_user
      authorize @topic
      if @topic.save
      flash[:notice] = "Topic was saved"
      redirect_to request.referer
    else
      flash[:error] = "There was an error saving your topic. Please try again."
      render :new
    end
  end

  def destroy
    @topic = Topic.find(params[:id])
    authorize @topic
    if @topic.destroy
      flash[:notice] = "\"#{@topic.title}\" was deleted successfully."
      redirect_to request.referer
    else
      flash[:error] = "topic was not delete, please try again"
      render :new
    end
  end


  def edit

  end

  private

  def topic_params
    params.require(:topic).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user)
    @topics = @user.topics.includes(:bookmarks)
    @new_bookmark = Bookmark.new
    @liked_bookmarks = @user.liked_bookmarks


end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @topics = Topic.all
    @new_topic = Topic.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/_bookmark.html.erb
 <div class="bookmark-container">
  <div>
    <p>
      Bookmark: <%= link_to bookmark.url, bookmark.url %>
      <%= render partial: 'likes/like', locals: { bookmark: bookmark} %>
      <p><small> <%=  bookmark.embedly[:description] %></small></p>
      <div>
        <%= image_tag(bookmark.embedly[:image]) %>
      </div>
    </p>
  </div>
</div>

app/views/bookmarks/_form.html.erb
<h3>New Bookmark<h3>
  <div class="col-md-8">
<%= form_for [topic, bookmark] do |f| %>
  <div class="new-bookmark-url">
  <%= f.text_field :url, class: 'form-control', placeholder: "Enter Bookmark" %>
  </div>
  <div class="new-bookmark-description">
    <%= f.text_field :description, class: 'form-control', placeholder: "provide description" %>
  </div>
  <div class="form-group">
  <%= f.submit "create bookmark", class:  'btn btn-success' %>
  </div>
<% end %>
</div>

app/views/bookmarks/edit.html.erb
<h1>Bookmarks#edit</h1>
<div class="col-md-8">
    <%= form_for @bookmark do |f| %>
      <div class="form-group">
        <%= f.label :url %>
        <%= f.text_field :url, class: 'form-control', placeholder: "update bookmark" %>
      </div>
      <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" type="text/css" href="http://fonts.googleleapis.com/css?family=Open+Sans:400,800,600,700,300">
  <link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="stylesheet" type="text/css" href="styles/normalize.css">
  <link rel="stylesheet" type="text/css" href="styles/main.css">
  <link href='https://fonts.googleapis.com/css?family=Architects+Daughter' rel='stylesheet' type='text/css'>


  <% if user_signed_in? %>
  Signed in as: <strong><%= current_user.email %></strong> |
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> -
  <%= link_to "My Profile", user_session_path, :class => 'navbar-link' %> -
  <%= link_to "Topics", welcome_index_path, :class => 'navbar-link' %>

  <% else %>
  <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link' %>
  <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link' %>
  <% end %>

  <title>Blocmark</title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= yield %>
</div>
</body>
</html>

app/views/likes/_like.html.erb
<% if true # policy(Like.new).create? %>
  <% if like = current_user.liked(bookmark) %>
    <%= link_to [bookmark, like], class: 'btn btn-danger btn-xs', method: :delete do %>
      <i class="glyphicon glyphicon-star-empty"> </i>&nbsp;
    <% end %>
  <% else %>
    <%= link_to [bookmark, Like.new], class: 'btn btn-primary btn-xs', method: :post do %>
      <i class="glyphicon glyphicon-star"> </i>&nbsp;
    <% end %>
  <% end %>
<% end %>

app/views/topics/_form.html.erb
<div class="col-md-8">
  <%= form_for topic do |f| %>
    <div class="form-group">
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter topic name" %>
  </div>

    <div class="form-group">
      <%= f.submit "create topic", class: 'btn btn-success'  %>
    </div>
  <% end %>
</div>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
  <div class="pigs">
<h3>Topics</h3>
</div>

<% @topics.each do |topic| %>
 <p><%= link_to topic.title %></p>
<% end %>
<h1>New Topic</h1>
<%= render partial: "topics/form", locals: {topic: @topic} %>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
div class="jumbotron">
    <div class="topics-show-container">
      <div class="pigs">
  <h1><%= @topic.title %></h1>
</div>

    <%= render partial: 'bookmarks/form', locals: {topic: @topic, bookmark: @new_bookmark} %>
    <div class="bookmark-collection"
      <%= render partial: "bookmarks/bookmark", collection: @topic.bookmarks %>
    </div>
  </div>
</div>
<div class="topics-show-footer">
<%= link_to "Back To Topics", root_path, method: :get, class: "btn btn-primary" %>
</div>
</div>

app/views/users/show.html.erb
<div class="users-jumbotron">
  <div class="users-container">
    <h2> Welcome <%= @user.username %>  </h2>
      <div class="row">
        <div class="col-md-4">
          <h3>My topics</h3>
          <% @topics.each do |topic|  %>
            <p><%= link_to topic.title, topic %></p>
            <p><%= link_to "Delete topic", topic, method: :delete, class: "btn btn-danger btn-xs" %></p>
            <% end %>
        </div>
        <div class="col-md-4">
          <div class="pigs">
          <h3>My Bookmarks!</h3>
        </div>
          <% @user.bookmarks.each do |bookmark| %>
            <p><%= link_to bookmark.url, bookmark.url %></p>
          <% end %>
        </div>
        <div class="col-md-4">
          <h3>Bookmarks I like!</h3>
          <p><% @liked_bookmarks.each do |bookmark| %></p>
            <%= render partial: 'bookmarks/bookmark', locals: { bookmark: bookmark} %>
            <% end %>
        </div>
        <div>
          <h4>See what other people are interested in</h4>
          <%= link_to "Go to topics", root_path, method: :get, class: "btn btn-info" %>
        </div>
      </div>
    </div>
  </div>

app/views/welcome/index.html.erb
<div class="topics-jumbotron">
    <div class="topics-container">
        <div class="topic-head">
          <h1>Welcome to Blocmarks</h1>
        </div>
          <div class="col-md-4">
            <p><strong> Select or create a topic that interests you. It can be anything!</strong> </p>
            </div>
            <div class="col-md-4">
              <p><strong> Follow the links to resources that will help you learn the things that interest you!</strong></p>
            </div>
            <div class="col-md-4">
              <p><strong> Share what you have learned by adding resources to topics!</strong></p>
              </div>
        </div>
        <div class="new-topic">
          <h3>New Topic</h3>

            <%= render partial: "topics/form", locals: {topic: @new_topic} %>
          </div>
            <div class="topic">
            <h3> choose a topic </h3>
              <% @topics.each do |topic| %>
                <p><strong><%= link_to topic.title, topic %></strong></p>
              <% end %>
            </div>


  </div>